# Generated by Django 5.2.17 on 2026-08-16 18:12

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='Filial nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.branch_image_path, verbose_name='Rasm')),
                ('map_link', models.URLField(blank=True, verbose_name='Google Maps havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('course', models.CharField(blank=True, max_length=120, verbose_name='Qaysi kurs?')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='Kurs nomi')),
                ('category', models.CharField(max_length=5, verbose_name='Toifa')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(blank=True, verbose_name="To'liq tavsif")),
                ('duration', models.CharField(blank=True, max_length=50, verbose_name='Davomiylik')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Narx')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.course_image_path, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name="Mashg'ulot nomi")),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Qisqa izoh')),
                ('description', models.TextField(blank=True, verbose_name="To'liq ma'lumot")),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.lesson_image_path, verbose_name='Rasm')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': "Mashg'ulot",
                'verbose_name_plural': "Mashg'ulotlar",
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.core.models.news_image_path, verbose_name='Rasm')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Chop etilgan sana')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='Sarlavha')),
                ('number', models.CharField(max_length=30, verbose_name="Raqam / ko'rsatkich")),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap/lucide icon nomi', max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Tri Zvezdy Avto Maktab', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.core.models.site_image_path, verbose_name='Logo')),
                ('hero_subtitle', models.CharField(default="SIFATLI TA'LIM — XAVFSIZ HAYOT", max_length=255, verbose_name='Hero subtitle')),
                ('hero_title', models.CharField(default='TRI ZVEZDY AVTO MAKTAB', max_length=255, verbose_name='Hero title')),
                ('hero_description', models.TextField(default="Eng sifatli darslar, tajribali o'qituvchilar va zamonaviy yondashuv bilan haydovchilikni oson va ishonchli o'rganing.", verbose_name='Hero matn')),
                ('phones', models.JSONField(blank=True, default=list, help_text='["990 077 170", "911 675 560"]', verbose_name='Telefonlar')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('webstorm_name', models.CharField(default='WebStorm', max_length=60)),
                ('webstorm_tagline', models.CharField(default='Zamonaviy web yechimlar va sifatli dasturlash xizmatlari', max_length=120)),
                ('webstorm_link', models.URLField(default='https://webstorm.uz', verbose_name='WebStorm havola')),
                ('webstorm_logo', models.ImageField(blank=True, null=True, upload_to=apps.core.models.site_image_path, verbose_name='WebStorm logo')),
                ('footer_description', models.TextField(default="Professional haydovchilik maktabi — sifatli ta'lim, tajribali ustozlar va zamonaviy yondashuv.", verbose_name='Footer tavsifi')),
                ('about_title', models.CharField(default='BIZ HAQIMIZDA', max_length=200, verbose_name='Biz haqimizda sarlavha')),
                ('about_content', models.TextField(default="Tri Zvezdy Avto Maktab — zamonaviy, sifatli va ishonchli haydovchilik ta'limini taqdim etuvchi avtomaktab.", verbose_name='Biz haqimizda matn')),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', 'Yangi ariza'), ('review', "Ko'rib chiqilmoqda"), ('contacted', "Bog'lanildi"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20, verbose_name='Holat')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Filial')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
