# Generated by Django 5.2.17 on 2026-08-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='work_hours',
            field=models.CharField(default='Har kuni 09:00 — 18:00', max_length=120, verbose_name='Ish vaqti'),
        ),
    ]
